spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AYB59uGMtTtVi0aYRHTpstHbtvgaljjA+TaCoLF+E9XXXySz7kGCJRF/v+Vfe3k3Bh6lPR9rgW1tGZFQA2nKgL3ykAO1bD3DVw/7Iv26dFi7PadeYRN0GQsYt1gRNzbrDimVBNVEpL3Cw/z68pL15nNwG1kFXVmWcrnUJVsaKiz3HDcxeQPbt2vfKGH5dA5uw+59RlMjOh9RxjnUylEBEu41KGmXFOQv9j/abIm5/NXueOQOquM53NXZXoea2X8HpmgUMDnVP1IydLYSBujWP4rFsAcnW5AccDhpTDJ50G1khUeOUvxlz1Wr3EMD6kKfSmajvt+qXwHNALacSJXo5J7UbPQsa8JG09fLwONygc1qIi/qaKZTotAPuQQhoAzEWfTICCBX2uDu/OS1mhzxHFn7AH2BjRcHRA57p/1204wYUdd5RIfdnndHbsG1ok6I9I9PB3axiTjNRfLAA3r7u0pycmrZADrwOKU8ViLuUeSnUH5cLPRR5gPjcr3j19GSUPo7KsOjrjUL82yxtrN8UJpBkgX6qaWkibD1r9O31yU5xw=='

token:
  expiration_time: 86400000
  secret: '{cipher}AYA6SvaJR0m4ulXaJCAO5L51y1TybjFd1009kQXQIT4vvDeyoW2r2Kd2OkzGf9anx/ZjQHBu4ETpIGjLIUee7l4dz8720U6r4QXcxlyr1FwU315iuje2l7cNXb40WqjXX+iEfa6JngwHxREYm2XKLWAmd9l4AEWMtJBBq3/0R79b84eCcHiaOOAUAf7loWpUKXiR/qTJZnQ//Rf5zVjobcmjrmQpytB3jgxlzr7LCiI/JFbm7k7td/lbOlN4N7Xgv01mKNXDgtRceqNQrzQID1lexS/NOvJ4H00A6RNWp0NphB718WAy18magmq71a4GNPk1+9m2h1ERnP2ddIutSGv2Qf6bJ64nN6CTdwU0jLnagO5vCBoH8hq1B3Z8BOuJU6apgNdbV0LyzwbexRMK22dcfjcM9W+kQGw4+UPkYE6TfQbfUN04d10zhPSG6oBKGxpzGAU+F7Nfl7bDzuqMFm26r34PzHr3iiVsioGit8A7JDGHEQHe5RkHB1jHOtPwwd0U7YdK5PUT9qhO0kEPH1lYrp2Pxo84qwXUW4PZq3JI8Lv9Y9chV4b4BovARIsyHZY='

gateway:
  ip: 192.168.219.102